node {
  stage('do something with git') {  
    sshagent (credentials: ['github-key']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote https://github.com/rsuslov/jenkins-course.git master |awk "{print $1}"'
    }
  }
}
